import type { CakeCustomizerCatalog, CakeCustomizerOption } from '@/lib/cake-customizer/types'

const PLACEHOLDER = (seed: string) =>
  `https://picsum.photos/seed/${encodeURIComponent(seed)}/400/280`

function option(
  partial: Omit<CakeCustomizerOption, 'isActive' | 'sortOrder'> & {
    sortOrder: number
  },
): CakeCustomizerOption {
  return { ...partial, isActive: true }
}

export const MOCK_CAKE_CUSTOMIZER_CATALOG: CakeCustomizerCatalog = {
  persons: [
    option({
      id: 'persons-6-8',
      type: 'persons',
      nameRo: '6–8 persoane',
      descriptionRo: 'Tort compact, ideal pentru familie sau prieteni apropiați.',
      imageUrl: PLACEHOLDER('cake-persons-6-8'),
      basePrice: 18000,
      personsCount: 7,
      sortOrder: 1,
    }),
    option({
      id: 'persons-10-12',
      type: 'persons',
      nameRo: '10–12 persoane',
      descriptionRo: 'Dimensiune echilibrată pentru petreceri mici.',
      imageUrl: PLACEHOLDER('cake-persons-10-12'),
      basePrice: 24000,
      personsCount: 11,
      sortOrder: 2,
    }),
    option({
      id: 'persons-15-20',
      type: 'persons',
      nameRo: '15–20 persoane',
      descriptionRo: 'Perfect pentru aniversări și evenimente medii.',
      imageUrl: PLACEHOLDER('cake-persons-15-20'),
      basePrice: 32000,
      personsCount: 18,
      sortOrder: 3,
    }),
    option({
      id: 'persons-25-30',
      type: 'persons',
      nameRo: '25–30 persoane',
      descriptionRo: 'Tort generos pentru sărbători mari.',
      imageUrl: PLACEHOLDER('cake-persons-25-30'),
      basePrice: 45000,
      personsCount: 28,
      sortOrder: 4,
    }),
  ],
  tiers: [
    option({
      id: 'tier-1',
      type: 'tier',
      nameRo: '1 etaj',
      descriptionRo: 'Simplu și elegant — un singur nivel.',
      imageUrl: PLACEHOLDER('cake-tier-1'),
      extraPrice: 0,
      tierCount: 1,
      sortOrder: 1,
    }),
    option({
      id: 'tier-2',
      type: 'tier',
      nameRo: '2 etaje',
      descriptionRo: 'Volum suplimentar, aspect festiv.',
      imageUrl: PLACEHOLDER('cake-tier-2'),
      extraPrice: 8000,
      tierCount: 2,
      sortOrder: 2,
    }),
    option({
      id: 'tier-3',
      type: 'tier',
      nameRo: '3 etaje',
      descriptionRo: 'Showstopper — tort impresionant cu trei niveluri.',
      imageUrl: PLACEHOLDER('cake-tier-3'),
      extraPrice: 15000,
      tierCount: 3,
      sortOrder: 3,
    }),
  ],
  sponges: [
    option({
      id: 'sponge-vanilla',
      type: 'sponge',
      nameRo: 'Blat vanilie',
      descriptionRo: 'Clasic, pufos, plăcut tuturor.',
      imageUrl: PLACEHOLDER('cake-sponge-vanilla'),
      extraPrice: 0,
      sortOrder: 1,
    }),
    option({
      id: 'sponge-cocoa',
      type: 'sponge',
      nameRo: 'Blat cacao',
      descriptionRo: 'Aromă intensă de ciocolată.',
      imageUrl: PLACEHOLDER('cake-sponge-cocoa'),
      extraPrice: 500,
      sortOrder: 2,
    }),
    option({
      id: 'sponge-red-velvet',
      type: 'sponge',
      nameRo: 'Red Velvet',
      descriptionRo: 'Culoare vibrantă, gust delicat.',
      imageUrl: PLACEHOLDER('cake-sponge-red-velvet'),
      extraPrice: 1200,
      sortOrder: 3,
    }),
    option({
      id: 'sponge-walnut',
      type: 'sponge',
      nameRo: 'Blat cu nucă',
      descriptionRo: 'Textură rustică, aromă caldă.',
      imageUrl: PLACEHOLDER('cake-sponge-walnut'),
      extraPrice: 800,
      sortOrder: 4,
    }),
  ],
  creams: [
    option({
      id: 'cream-chocolate',
      type: 'cream',
      nameRo: 'Cremă ciocolată',
      descriptionRo: 'Intensă și cremoasă.',
      imageUrl: PLACEHOLDER('cake-cream-chocolate'),
      extraPrice: 0,
      sortOrder: 1,
    }),
    option({
      id: 'cream-vanilla',
      type: 'cream',
      nameRo: 'Cremă vanilie',
      descriptionRo: 'Fină, echilibrată, versatilă.',
      imageUrl: PLACEHOLDER('cake-cream-vanilla'),
      extraPrice: 0,
      sortOrder: 2,
    }),
    option({
      id: 'cream-berry',
      type: 'cream',
      nameRo: 'Cremă fructe de pădure',
      descriptionRo: 'Acidulată și proaspătă.',
      imageUrl: PLACEHOLDER('cake-cream-berry'),
      extraPrice: 900,
      sortOrder: 3,
    }),
    option({
      id: 'cream-pistachio',
      type: 'cream',
      nameRo: 'Cremă fistic',
      descriptionRo: 'Aromă premium, culoare delicată.',
      imageUrl: PLACEHOLDER('cake-cream-pistachio'),
      extraPrice: 1500,
      sortOrder: 4,
    }),
  ],
  glazes: [
    option({
      id: 'glaze-buttercream',
      type: 'glaze',
      nameRo: 'Buttercream',
      descriptionRo: 'Finisaj clasic, neted și cremos.',
      imageUrl: PLACEHOLDER('cake-glaze-buttercream'),
      extraPrice: 0,
      sortOrder: 1,
    }),
    option({
      id: 'glaze-ganache',
      type: 'glaze',
      nameRo: 'Ganache ciocolată',
      descriptionRo: 'Strălucitor, intens, luxos.',
      imageUrl: PLACEHOLDER('cake-glaze-ganache'),
      extraPrice: 600,
      sortOrder: 2,
    }),
    option({
      id: 'glaze-fondant',
      type: 'glaze',
      nameRo: 'Fondant',
      descriptionRo: 'Suprafață perfectă pentru decor.',
      imageUrl: PLACEHOLDER('cake-glaze-fondant'),
      extraPrice: 1200,
      sortOrder: 3,
    }),
    option({
      id: 'glaze-naked',
      type: 'glaze',
      nameRo: 'Naked cake',
      descriptionRo: 'Blat vizibil, stil natural și modern.',
      imageUrl: PLACEHOLDER('cake-glaze-naked'),
      extraPrice: 400,
      sortOrder: 4,
    }),
  ],
  themes: [
    option({
      id: 'theme-classic',
      type: 'theme',
      nameRo: 'Clasic',
      descriptionRo: 'Elegant, atemporal.',
      imageUrl: PLACEHOLDER('cake-theme-classic'),
      extraPrice: 0,
      sortOrder: 1,
    }),
    option({
      id: 'theme-floral',
      type: 'theme',
      nameRo: 'Floral',
      descriptionRo: 'Flori de zahăr sau naturale.',
      imageUrl: PLACEHOLDER('cake-theme-floral'),
      extraPrice: 2500,
      sortOrder: 2,
    }),
    option({
      id: 'theme-minimal',
      type: 'theme',
      nameRo: 'Minimal',
      descriptionRo: 'Linii curate, culori discrete.',
      imageUrl: PLACEHOLDER('cake-theme-minimal'),
      extraPrice: 1500,
      sortOrder: 3,
    }),
    option({
      id: 'theme-kids',
      type: 'theme',
      nameRo: 'Copii',
      descriptionRo: 'Personaje, culori vesele, figurine.',
      imageUrl: PLACEHOLDER('cake-theme-kids'),
      extraPrice: 3000,
      sortOrder: 4,
    }),
  ],
  colors: [
    option({
      id: 'color-white',
      type: 'color',
      nameRo: 'Alb',
      descriptionRo: 'Curat și luminos.',
      imageUrl: PLACEHOLDER('cake-color-white'),
      swatchColor: '#FAF7F2',
      extraPrice: 0,
      sortOrder: 1,
    }),
    option({
      id: 'color-blush',
      type: 'color',
      nameRo: 'Roz pudrat',
      descriptionRo: 'Delicat, romantic.',
      imageUrl: PLACEHOLDER('cake-color-blush'),
      swatchColor: '#F2C4C4',
      extraPrice: 500,
      sortOrder: 2,
    }),
    option({
      id: 'color-sage',
      type: 'color',
      nameRo: 'Verde salvie',
      descriptionRo: 'Natural, calm.',
      imageUrl: PLACEHOLDER('cake-color-sage'),
      swatchColor: '#A8B5A0',
      extraPrice: 500,
      sortOrder: 3,
    }),
    option({
      id: 'color-chocolate',
      type: 'color',
      nameRo: 'Ciocolată',
      descriptionRo: 'Cald, rustic.',
      imageUrl: PLACEHOLDER('cake-color-chocolate'),
      swatchColor: '#6B4F3A',
      extraPrice: 500,
      sortOrder: 4,
    }),
  ],
}

/** Personalization fees (cents) — applied client-side when fields are filled */
export const PERSONALIZATION_FEES = {
  customText: 1500,
  color: 1000,
  theme: 2500,
} as const
